categories: [Data Managers]
description: Fetch FASTA data from NCBI RefSeq and update all_fasta data table
long_description: |
  This data manager fetches FASTA format collections of proteins, nucleotides (genomic DNA) and RNA
  from NCBI's RefSeq data collection.
remote_repository_url: https://github.com/pvanheus/refseq_fasta_data_manager
type: unrestricted
name: data_manager_fetch_refseq
owner: sanbi-uwc
